# Generated by Django 5.0 on 2023-12-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="play",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="theatre.play",
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="theatre_hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="theatre.theatrehall",
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="actor",
            field=models.ManyToManyField(related_name="plays", to="theatre.actor"),
        ),
        migrations.AlterField(
            model_name="play",
            name="genre",
            field=models.ManyToManyField(related_name="plays", to="theatre.genre"),
        ),
    ]
